export const products = [
  {
    id: 0,
    name: "Apple Watch Pro",
    price: 106,
    img: "/images/apple-watch-pro.jpg",
    inStock: 0,
    fastDelivery: true,
    rating: 1,
  },
  {
    id: 1,
    name: "Denim Jeans",
    price: 10,
    img: "/images/denim-jeans.jpg",
    inStock: 3,
    fastDelivery: true,
    rating: 2,
  },
  {
    id: 2,
    name: "Addidas High Tops",
    price: 150,
    img: "/images/hightops.jpg",
    inStock: 0,
    fastDelivery: true,
    rating: 3,
  },
  {
    id: 3,
    name: "Jacket",
    price: 106,
    img: "/images/lightdress.jpg",
    inStock: 6,
    fastDelivery: false,
    rating: 4,
  },
  {
    id: 4,
    name: "Leather Wrist Watch",
    price: 50,
    img: "/images/leather-watch.jpg",
    inStock: 7,
    fastDelivery: false,
    rating: 5,
  },
  {
    id: 5,
    name: "Leather Bag",
    price: 20,
    img: "/images/leatherbags.jpg",
    inStock: 8,
    fastDelivery: true,
    rating: 4,
  },
  {
    id: 6,
    name: "Nike Air",
    price: 10,
    img: "/images/nike-air.jpg",
    inStock: 3,
    fastDelivery: true,
    rating: 2,
  },
  {
    id: 7,
    name: "iphone 12",
    price: 300,
    img: "/images/phone1.jpg",
    inStock: 5,
    fastDelivery: false,
    rating: 5,
  },
  {
    id: 8,
    name: "Light Dress",
    price: 12,
    img: "/images/jacket.jpg",
    inStock: 1,
    fastDelivery: true,
    rating: 4,
  },
  {
    id: 9,
    name: "Iphone 12 Black",
    price: 320,
    img: "/images/iphone12-black.jpg",
    inStock: 0,
    fastDelivery: false,
    rating: 1,
  },
  {
    id: 10,
    name: "Iphone 11",
    price: 270,
    img: "/images/phone2.jpg",
    inStock: 6,
    fastDelivery: false,
    rating: 4,
  },
  {
    id: 11,
    name: "Michael Cors Wristwatch",
    price: 78,
    img: "/images/michael-cors wristwatch.jpg",
    inStock: 0,
    fastDelivery: false,
    rating: 2,
  },
];
